apiVersion: core.oam.dev/v1beta1
kind: Application
metadata:
  name: sre-app
  namespace: default
spec:
  components:
    - name: sre-app
      type: webservice
      properties:
        image: harbor-alpha1.eniot.io/op/pythondjango:master_20230227172425 # {"$imagepolicy":"default:image-gitops"}
        secretRef: test-harbor-secret
        port: 8080
        cmd: ["python", "manage.py", "runserver", "127.0.0.0:8080"]

